version = 1
SPDX-PackageName = "autonomous-operations.dev"
SPDX-PackageDownloadLocation = "https://github.com/autonomous-operations-platform/website"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and Autonomous Operations contributors"
SPDX-License-Identifier = "Apache-2.0"
